<?xml version="1.0" encoding="UTF-8"?><testrun duration="5296" footerText="Generated by PyCharm on 2/26/20, 2:48 PM" name="pytest for test__after_the_rain.test__after_the_rain__stress">
    <count name="total" value="2"/>
    <count name="failed" value="1"/>
    <count name="passed" value="1"/>
    <config nameIsGenerated="true" configId="tests" name="pytest for test__after_the_rain.test__after_the_rain__stress">
        <module name="algorithms"/>
        <option name="INTERPRETER_OPTIONS" value=""/>
        <option name="PARENT_ENVS" value="true"/>
        <option name="SDK_HOME" value=""/>
        <option name="WORKING_DIRECTORY" value="/home/deimos/programacion/github/algorithms/tests"/>
        <option name="IS_MODULE_SDK" value="true"/>
        <option name="ADD_CONTENT_ROOTS" value="true"/>
        <option name="ADD_SOURCE_ROOTS" value="true"/>
        <option name="_new_keywords" value="&quot;&quot;"/>
        <option name="_new_additionalArguments" value="&quot;&quot;"/>
        <option name="_new_target" value="&quot;test__after_the_rain.test__after_the_rain__stress&quot;"/>
        <option name="_new_targetType" value="&quot;PYTHON&quot;"/>
    </config>
    <suite duration="5296" locationUrl="python&lt;/home/deimos/programacion/github/algorithms/tests&gt;://tests" name="tests" status="failed">
        <suite duration="5296" locationUrl="python&lt;/home/deimos/programacion/github/algorithms/tests&gt;://tests.test__after_the_rain" name="test__after_the_rain" status="failed">
            <test duration="1" locationUrl="python&lt;/home/deimos/programacion/github/algorithms/tests&gt;://tests.test__after_the_rain.test__after_the_rain__stress" name="test__after_the_rain__stress" metainfo="test__after_the_rain__stress" status="passed">
                <output type="stdout">PASSED             [100%]
</output>
            </test>
            <test duration="5295" locationUrl="python&lt;/home/deimos/programacion/github/algorithms/tests&gt;://tests.test__after_the_rain.test__after_the_rain__stress_teardown" name="test__after_the_rain__stress_teardown" status="failed">
                <output type="stderr">tests/test__after_the_rain.py:68 (test__after_the_rain__stress)
yield_fixture function has more than one &amp;#39;yield&amp;#39;:
    @fixture()
    def stress_case(request):
        random = Random(0)
        for length in range(100):
            heights = [random.randrange(10) for _ in range(length)]
            answer = after_the_rain_naive(heights)
            yield {&amp;quot;heights&amp;quot;: heights, &amp;quot;answer&amp;quot;: answer}
/home/deimos/programacion/github/algorithms/tests/test__after_the_rain.py:45
</output>
            </test>
        </suite>
    </suite>
</testrun>
