<?xml version="1.0" encoding="UTF-8"?><testrun footerText="Generated by PyCharm on 2/26/20, 11:28 AM" name="pytest for test__after_the_rain.test__after_the_rain__examples">
    <count name="total" value="1"/>
    <count name="failed" value="1"/>
    <config nameIsGenerated="true" configId="tests" name="pytest for test__after_the_rain.test__after_the_rain__examples">
        <module name="algorithms"/>
        <option name="INTERPRETER_OPTIONS" value=""/>
        <option name="PARENT_ENVS" value="true"/>
        <option name="SDK_HOME" value=""/>
        <option name="WORKING_DIRECTORY" value="/home/deimos/programacion/github/algorithms/tests"/>
        <option name="IS_MODULE_SDK" value="true"/>
        <option name="ADD_CONTENT_ROOTS" value="true"/>
        <option name="ADD_SOURCE_ROOTS" value="true"/>
        <option name="_new_keywords" value="&quot;&quot;"/>
        <option name="_new_additionalArguments" value="&quot;&quot;"/>
        <option name="_new_target" value="&quot;test__after_the_rain.test__after_the_rain__examples&quot;"/>
        <option name="_new_targetType" value="&quot;PYTHON&quot;"/>
    </config>
    <suite locationUrl="python&lt;/home/deimos/programacion/github/algorithms/tests&gt;://tests" name="tests" status="failed">
        <suite locationUrl="python&lt;/home/deimos/programacion/github/algorithms/tests&gt;://tests.test__after_the_rain" name="test__after_the_rain" status="failed">
            <test locationUrl="python&lt;/home/deimos/programacion/github/algorithms/tests&gt;://tests.test__after_the_rain.top_level_collect" name="top_level_collect" status="failed">
                <output type="stderr">tests/test__after_the_rain.py:None (tests/test__after_the_rain.py)
../../../../.virtualenvs/algorithms/lib/python3.6/site-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../../../../.virtualenvs/algorithms/lib/python3.6/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
&amp;lt;frozen importlib._bootstrap&amp;gt;:971: in _find_and_load
    ???
&amp;lt;frozen importlib._bootstrap&amp;gt;:955: in _find_and_load_unlocked
    ???
&amp;lt;frozen importlib._bootstrap&amp;gt;:656: in _load_unlocked
    ???
&amp;lt;frozen importlib._bootstrap&amp;gt;:626: in _load_backward_compatible
    ???
../../../../.virtualenvs/algorithms/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
test__after_the_rain.py:3: in &amp;lt;module&amp;gt;
    from src.after_the_rain import after_the_rain
E     File &amp;quot;/home/deimos/programacion/github/algorithms/src/after_the_rain.py&amp;quot;, line 7
E       bucket = =
E                ^
E   SyntaxError: invalid syntax
</output>
            </test>
        </suite>
    </suite>
</testrun>
